# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 5d3d5b74788da74abcda114aa6697f7197ffe9ebdf2526cb765b5d093949457a0d362c7b3d39c3602b97d1cfe211daf3a3e10fb8c94e08b27ae7f21a11b46d63

test:
  secret_key_base: 452b6e594a7315c92de76eee86319b19b43f5fa6c986561372b5316db6c8e4820a4c2d6376c427783ca963dd639f51d746581c65b5db3536d1b263a7f910d85f

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
